.TH TIKIBLOCKS 1 tikiblocks\-VERSION
.SH NAME
tikiblocks \- status bar update tool
.SH SYNOPSIS
.B tikiblocks
.RB [ \-v ]
.SH DESCRIPTION
tikiblocks is a status bar update tool not tied to X or Wayland. It produces
blocks of text, which may also include icons or emojis if your font-environment
is configured appropriately.
.SH CUSTOMIZATION
tikiblocks outputs to stdout or to a named pipe (for somebar), and is configurable
via $XDG_CONFIG_HOME/tikiblocks/tikiblocks.json.
.SH BUGS
Send all bug reports with a patch to github@mikewatkins.ca.
